In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Loading the Dataset

In [5]:
df = pd.read_csv('Train.csv')
print(df.columns)

Index(['feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5',
       'target'],
      dtype='object')


In [20]:
y = list(df.get('target'))
print(y)

[-82.1546665555647, -48.89796018174453, 77.27037069642637, -2.988580812931591, -37.5967221222241, -122.40526319541374, 1.4137409588302887, -13.30654265469312, -25.754697999669503, -57.07775436628268, -41.96469420406653, 78.08048569390992, -93.63936149342364, -133.31763800289798, -159.59081532087728, 25.327815233768806, -59.74138549330047, 8.007755826242253, 13.124382888236198, 50.72980227199659, -56.4102812514651, 244.66624870168314, -139.5338955552169, -172.59950283087056, 209.46784502825741, 177.70294146087207, 27.292169962333787, -34.38300171387427, -50.97677960916407, 217.97681299553304, -174.74383975662468, -130.1860152217056, 17.351203986768734, -16.904883876807283, -151.77717604193487, 79.19716952666448, -89.5291541125977, 192.01169431924302, 64.52937294396081, -95.44106952453971, -85.82155198713791, -145.48099930690032, 30.754974047787403, -73.74052127905831, -173.7796732621922, -101.7139775384914, -379.8297939471095, 30.518018165592764, 23.08755981830814, 86.77782134002935, -6

In [8]:
df.values

array([[ 2.93416239e-01, -9.45598713e-01, -4.21105147e-01,
         4.06816021e-01,  5.25661832e-01, -8.21546666e+01],
       [-8.36084081e-01, -1.89228039e-01, -7.76402618e-01,
        -1.05383124e+00,  5.97996852e-01, -4.88979602e+01],
       [ 2.36425114e-01,  1.32836018e-01, -1.47722982e-01,
         6.99853963e-01, -1.87364163e-01,  7.72703707e+01],
       ...,
       [ 1.04417694e+00, -8.99206485e-01,  1.73039905e+00,
        -1.87105676e+00,  4.42519647e-01, -1.07510508e+02],
       [-1.26917290e+00, -5.05215916e-03,  1.85766873e+00,
        -1.08036482e+00,  7.36333937e-01, -4.73415578e+01],
       [-1.88400025e+00, -8.49427430e-01, -1.45227035e+00,
         4.88613076e-01,  1.45957580e+00, -1.15939003e+02]])

In [23]:
x = df.values[:,0:5]
print(x)
y = df.values[:,5]
print(y)

[[ 0.29341624 -0.94559871 -0.42110515  0.40681602  0.52566183]
 [-0.83608408 -0.18922804 -0.77640262 -1.05383124  0.59799685]
 [ 0.23642511  0.13283602 -0.14772298  0.69985396 -0.18736416]
 ...
 [ 1.04417694 -0.89920649  1.73039905 -1.87105676  0.44251965]
 [-1.2691729  -0.00505216  1.85766873 -1.08036482  0.73633394]
 [-1.88400025 -0.84942743 -1.45227035  0.48861308  1.4595758 ]]
[ -82.15466656  -48.89796018   77.2703707  ... -107.51050797  -47.34155781
 -115.93900296]


In [24]:
print(x.shape)
print(y.shape)

(1600, 5)
(1600,)


## Training the model

In [27]:
from sklearn.linear_model import LinearRegression

In [28]:
# 1. Creating an object
model = LinearRegression(normalize=True)

In [29]:
# 2. Training the model
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

In [30]:
# 3. Printing the coefficients
print(model.coef_)
print(model.intercept_)

[29.68187118 92.66247759  8.28062089 44.76773522  2.51916121]
4.990966735574959


## Acuracy of Prediction

In [31]:
## Accuracy of prediction on the training data
model.score(x,y)

0.9660939669975616

In [33]:
## Loading the test data
dftest = pd.read_csv('Test.csv')
x_test = dftest.values

In [38]:
y_test = model.predict(x_test)
print(type(y_test))
# print(x_test)
# print(y_test)
## Accuracy prediction of the test data
print(model.score(x_test,y_test))

<class 'numpy.ndarray'>
1.0
